language: python
python:
  - "3.6"
  - "pypy3.5"

install:
  - pip install -r requirements
service:
  - redis-server
script:
  - python shahragard/manage.py makemigrations
  - python shahragard/manage.py makemigrations user
  - python shahragard/manage.py makemigrations trip
  - python shahragard/manage.py migrate
  - python shahragard/manage.py migrate user
  - python shahragard/manage.py migrate trip
  - python shahragard/manage.py test user
  - python shahragard/manage.py test search
