language: python
python:
  - "3.7"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements
# command to run tests
script:
  - python shahragard/manage.py test user
  - python shahragard/manage.py test search
